#ifndef CPPDISCORD_CHANNEL_TYPE_H
#define CPPDISCORD_CHANNEL_TYPE_H

enum channel_type {
    GUILD_TEXT = 0,
    DM = 1,
    GUILD_VOICE = 2,
    GROUP_DM = 3,
    GUILD_CATEGORY = 4,
    GUILD_NEWS = 5,
    GUILD_STORE
};

#endif //CPPDISCORD_CHANNEL_TYPE_H
