#ifndef CPPDISCORD_CONTENT_FILTER_LEVEL_H
#define CPPDISCORD_CONTENT_FILTER_LEVEL_H

enum content_filter_level{
    DISABLED = 0,
    MEMBERS_WITHOUT_ROLES = 1,
    ALL_MEMBERS = 2
};

#endif //CPPDISCORD_CONTENT_FILTER_LEVEL_H
